[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
massa_rust_sc = { path = "../massa_rust_sc" }

# [target.wasm32-unknown-unknown]
# runner = "target/debug/massa_sc_runner"
